### ISSUE TITLE
Update build dependency versions

### ISSUE THREAD

**Issue by kgabor** [JaneliaSciComp/BigStitcher-Spark#27]
I need to update `bigdataviewer-omezarr` dependency version, so I'll try to harmonize more or less with the Fiji released versions the other packages in the pom.

**Comment by kgabor** [comment]
https://github.com/JaneliaSciComp/BigStitcher-Spark/pull/28
I reverted back the other packages due to new error in creating groups by N5Writer in aws. We'll address this later.
The problem is, I think, that `setup0/timepoint0/s0` does not exist while setDatasetAttributes tries to read it in already before setting them.

```
org.janelia.saalfeldlab.n5.N5Exception$N5IOException: setup0/timepoint0/s0 is not a group or dataset.
	at org.janelia.saalfeldlab.n5.GsonKeyValueN5Writer.setAttributes(GsonKeyValueN5Writer.java:154)
	at org.janelia.saalfeldlab.n5.N5Writer.setDatasetAttributes(N5Writer.java:138)
	at org.janelia.saalfeldlab.n5.N5Writer.createDataset(N5Writer.java:206)
	at org.janelia.saalfeldlab.n5.N5Writer.createDataset(N5Writer.java:228)
	at net.preibisch.bigstitcher.spark.AffineFusion.call(AffineFusion.java:361)
```
